Fix unitary tests in local
canonical/craft-cli pull request #106
Opened 2022-07-07 10:43 UTC by sergio-costas

When running "make test-units" from a shell, several tests fail
with the error:

`  RuntimeError: Emitter needs to be initiated first`

This patch fixes this by initializing the 'emit' object.

Fix https://github.com/canonical/craft-cli/issues/105

- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

2022-07-11 19:17 UTC, facundobatista commented
Which test is failing for you?

2022-07-11 19:57 UTC, facundobatista requested changes
Hello! 

I don't like initiating the emitter at module level "just in case", if we have a race condition or something similar, we need to understand what is going on.

FTR, local tests run ok for me and other people. Let's follow up on this in the issue or in the chat. Thanks!

2022-07-12 11:24 UTC, sergio-costas commented
> Which test is failing for you?

This is the output: https://pastebin.canonical.com/p/YmwnkSF7Hq/

2022-07-12 11:39 UTC, sergio-costas commented
My fault: I forgot to enable the venv.

Sorry.

2022-07-12 11:39 UTC, closed without merging