Fix typos and markdowns
canonical/craft-cli pull request #118
Opened 2022-08-16 13:09 UTC by kianmeng

Found via these commands:

    codespell .
    markdownlint *.md

- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

2022-08-18 11:34 UTC, facundobatista requested changes
Hello! Thanks for this PR! 

While it's fine for the real English typos, all other aesthetic changes should be reverted (I added inline comments). After that we can land it.

Thanks again!

2022-08-18 11:34 UTC, facundobatista commented on HOWTO_RELEASE.md
> +    xdg-open <https://github.com/canonical/craft-cli/tags>
This is wrong, it will make the command to redirect input/output instead of passing the argument.

2022-08-18 11:34 UTC, facundobatista commented on README.md
> +- a framework to define and execute application commands, which involves
Do not cut the lines, just let them flow. It's slightly worse when you see it not rendered, but you don't get the "lot of lines rewrapping diff mess" when changing the text.

2022-08-18 11:34 UTC, facundobatista commented on HOWTO_RELEASE.md
> -
It's good to have two lines before titles, helps the eye separation. It's innocuous when rendered, too.

2022-08-18 17:17 UTC, facundobatista approved these changes
Thanks!

2022-08-18 17:18 UTC, merged

2022-08-19 05:24 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: